### ISSUE TITLE
UnicodeDecodeError: 'charmap' can't decode byte 0x88

### ISSUE THREAD

**Issue by kaytonkla** [victorca25/BasicSR#43] opened 2021-04-13 14:53 UTC
Tried to train a model, always end up with this error in cmd.
![error](https://user-images.githubusercontent.com/16862130/114573499-9eee8980-9ca2-11eb-899f-e0392bdf5945.PNG)

**Comment by victorca25** [comment] 2021-04-14 05:50
Hello! Looks like there is an error in your yaml file. The literal error is a problem interpreting a character, but it's hard to tell exactly what the issue is. Try reviewing the file for uncommon characters and if necessary, prepare it again from scratch to be certain there are no errors. You can also try parsing it with a linter to see if it helps finding the error: http://www.yamllint.com/

**Comment by kaytonkla** [comment] 2021-04-14 06:38
The linter say the yaml file is valid, I downloaded a fresh copy and run it, still ends up with the same error with different position.

**Comment by victorca25** [comment] 2021-04-14 17:22
In that case probably the best bet would be to share your yaml in the Discord channel and see if someone can spot the issue, sometimes they are hard to find, but more eyes can help

**Comment by kaytonkla** [comment] 2021-04-14 18:10
Got this error after starting up for scratch, sometimes it jumps to the same Unicode error I reported, could this be something?
![error2](https://user-images.githubusercontent.com/16862130/114758498-3c22ee00-9d87-11eb-8b7a-9fb1871287a0.PNG)

**Comment by victorca25** [comment] 2021-04-14 18:39
Double check the command, you're telling test.py to load a "train template.yml" file that doesn't exist

**Comment by victorca25** [comment] 2021-04-24 14:11
I'll close the issue for now, if problems persist, please reopen or ask in the Discord channel as well, more people could help!

**Closed by victorca25** 2021-04-24 14:11 UTC
